<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.0;net6.0;net8.0</TargetFrameworks>
    <VersionPrefix>0.2.1</VersionPrefix>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/jakegough/jaytwo.UrlHelper.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="jaytwo.UrlHelper.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" Link="README.md" />
  </ItemGroup>

</Project>
